# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# Aqui declaramos as gems que vamos usar no projeto
gem 'json'

# Para instalar as gems, basta rodar o comando: bundle install